import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "moviebot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh-hans" className="h-full bg-white">
      <body className={`h-full ${inter.fontFamily}`}>{children}</body>
    </html>
  );
}
