import { Inter } from "next/font/google";
import classnames from "classnames";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "moviebot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh-hans" className="h-full">
      <body className={classnames("h-full bg-gray-950 text-white", inter.fontFamily)}>
        {children}
      </body>
    </html>
  );
}
